name: Bild and Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Instrall dependencies
        run: npm install
      - name: Run tests
        run: npm test

  security_test:
    needs: unit_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Instrall dependencies
        run: npm install
      - name: Run tests
        run: npm test

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: security_test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: JorgeLNJunior/render-deploy-action@v1.4.5
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-deploy: true
